export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';

export const USER_GET_INFO = 'USER_GET_INFO'
export const USER_UPDATE_ADDRESS = 'USER_UPDATE_ADDRESS'
export const USER_ADD_ADDRESS = 'USER_ADD_ADDRESS'
